CREATE TYPE "user_type" AS ENUM (
  'person',
  'store',
  'bank'
);

CREATE TYPE "transaction_type" AS ENUM (
  'credit',
  'debit'
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "cpf_cnpj" varchar(14) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "user_type" user_type NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "Transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payer" int NOT NULL,
  "payee" int NOT NULL,
  "transaction_type" transaction_type NOT NULL,
  "amount" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "is_valid" boolean DEFAULT true
);

ALTER TABLE "Transactions" ADD FOREIGN KEY ("payer") REFERENCES "Users" ("id");

ALTER TABLE "Transactions" ADD FOREIGN KEY ("payee") REFERENCES "Users" ("id");

-- passwords = passwor1d@

INSERT INTO public."Users"(
	email, password, cpf_cnpj, name, user_type)
	VALUES ('bank@email.com', '$2a$14$lPwJOUpOf7OzUbOPftw.SOHGnsdcMuTWjM.ZzTrkKzbu0ENSUAQHi', '99999999999999', 'bank', 'bank');

INSERT INTO public."Users"(
	email, password, cpf_cnpj, name, user_type)
	VALUES ('person1@email.com', '$2a$14$lPwJOUpOf7OzUbOPftw.SOHGnsdcMuTWjM.ZzTrkKzbu0ENSUAQHi', '00011111111111', 'person 1', 'person');

INSERT INTO public."Users"(
	email, password, cpf_cnpj, name, user_type)
	VALUES ('person2@email.com', '$2a$14$lPwJOUpOf7OzUbOPftw.SOHGnsdcMuTWjM.ZzTrkKzbu0ENSUAQHi', '00022222222222', 'person 2', 'person');

INSERT INTO public."Users"(
	email, password, cpf_cnpj, name, user_type)
	VALUES ('store1@email.com', '$2a$14$lPwJOUpOf7OzUbOPftw.SOHGnsdcMuTWjM.ZzTrkKzbu0ENSUAQHi', '11111111111111', 'store 1', 'store');

INSERT INTO public."Transactions"(
	payer, payee, transaction_type, amount)
	VALUES (1, 2, 'credit', 100000);

INSERT INTO public."Transactions"(
	payer, payee, transaction_type, amount)
	VALUES (1, 2, 'debit', 5000);

INSERT INTO public."Transactions"(
	payer, payee, transaction_type, amount)
	VALUES (1, 3, 'credit', 100000);

INSERT INTO public."Transactions"(
	payer, payee, transaction_type, amount)
	VALUES (1, 3, 'debit', 10000);